services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry123
      POSTGRES_DB: telemetry_db

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telemetry -d telemetry_db"]
      interval: 5s
      timeout: 5s
      retries: 10


  snmp-device:
    image: polinux/snmpd

    volumes:
      - ./snmp/snmpd.conf:/etc/snmp/snmpd.conf:ro


  snmp-device-2:
    image: polinux/snmpd

    volumes:
      - ./snmp/snmpd.conf:/etc/snmp/snmpd.conf:ro


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "50051:50051"


  api:
    build:
      context: .
      dockerfile: backend/Dockerfile

    command:
      [
        "uvicorn",
        "api:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"


  collector:
    build:
      context: .
      dockerfile: collector/Dockerfile

    depends_on:
      - snmp-device
      - snmp-device-2
      - backend


  grafana:
    image: grafana/grafana

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana


volumes:
  grafana-data:
  postgres-data: