# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\"\xb3\x01\n\rTelemetryData\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x14\n\x0cincoming_bps\x18\x02 \x01(\x01\x12\x14\n\x0coutgoing_bps\x18\x03 \x01(\x01\x12\x1c\n\x14incoming_utilization\x18\x04 \x01(\x01\x12\x1c\n\x14outgoing_utilization\x18\x05 \x01(\x01\x12\x12\n\nlatency_ms\x18\x06 \x01(\x01\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\"\x1e\n\x0cTelemetryAck\x12\x0e\n\x06status\x18\x01 \x01(\t2@\n\x10TelemetryService\x12,\n\x0bSendMetrics\x12\x0e.TelemetryData\x1a\r.TelemetryAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYDATA']._serialized_start=20
  _globals['_TELEMETRYDATA']._serialized_end=199
  _globals['_TELEMETRYACK']._serialized_start=201
  _globals['_TELEMETRYACK']._serialized_end=231
  _globals['_TELEMETRYSERVICE']._serialized_start=233
  _globals['_TELEMETRYSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
